In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from numpy import *
from pymatgen.core.operations import SymmOp
from IPython.display import Image

# --------------------------------------------------------
# Procedure de telechargement du fichier .cif du LiCoO2.
# --------------------------------------------------------

with MPRester("L41ZHCirMyRASy8QHJEO") as m:
    
    structure = m.get_structure_by_material_id("mp-22526")
    
    myCifWritten = CifWriter(structure)
    
    myCifWritten.write_file('LiCoO2_mp-22526_symmetrized.cif')
    
# --------------------------------------------------------
# Etude des trois elements de symetrie.
# --------------------------------------------------------
    
    Sym_1 = SymmOp.from_xyz_string('x-y, -y, -z') # 9
    Li0 = [0.,0.,1.]
    Li0_Sym = Sym_1.operate(Li0)
    
    print("Atome initial : ", Li0)
    print("\nAtome final : ", Li0_Sym)
    print("\nOperation de symétrie : \n",Li0_Sym, '=',Sym_1.translation_vector, "+ \n",Sym_1.rotation_matrix, '.',Li0)
    print(" =================================================================")
    
# --------------------------------------------------------
    
    Sym_2 = SymmOp.from_xyz_string('-x+y, y, z') # 10
    Co1 = [0.,0.5,1.]
    Co1_Sym = Sym_2.operate(Co1)
    
    print("Atome initial : ", Co1)
    print("\nAtome final : ", Co1_Sym)
    print("\nOperation de symétrie : \n",Co1_Sym, '=',Sym_2.translation_vector, "+ \n",Sym_2.rotation_matrix, '.',Li0)
    print(" =================================================================")
    
# --------------------------------------------------------
    
    Sym_3 = SymmOp.from_xyz_string('-y+2/3, -x+1/3, z+1/3') # 20
    O2 = [0.,0.,1.]
    O2_Sym = Sym_3.operate(O2)
    
    print("Atome initial : ", O2)
    print("\nAtome final : ", O2_Sym)
    print("\nOperation de symétrie : \n",O2_Sym, '=',Sym_3.translation_vector, "+ \n",Sym_3.rotation_matrix, '.',O2)
    print(" =================================================================")
# --------------------------------------------------------

Atome initial :  [0.0, 0.0, 1.0]

Atome final :  [ 0.  0. -1.]

Operation de symétrie : 
 [ 0.  0. -1.] = [0. 0. 0.] + 
 [[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]] . [0.0, 0.0, 1.0]
Atome initial :  [0.0, 0.5, 1.0]

Atome final :  [0.5 0.5 1. ]

Operation de symétrie : 
 [0.5 0.5 1. ] = [0. 0. 0.] + 
 [[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] . [0.0, 0.0, 1.0]
Atome initial :  [0.0, 0.0, 1.0]

Atome final :  [0.66666667 0.33333333 1.33333333]

Operation de symétrie : 
 [0.66666667 0.33333333 1.33333333] = [0.66666667 0.33333333 0.33333333] + 
 [[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]] . [0.0, 0.0, 1.0]
